{
 "title": "Liquidity",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "histogramWidth",
    "label": "Histogram width",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Liveness",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n  ((SELECT offset FROM liquidity_analytics.tag_offsets WHERE tag = \"zone-event\" ORDER BY offset DESC LIMIT 1)\n  /\n  (SELECT ordering FROM liquidity_journal.journal ORDER BY ordering DESC LIMIT 1))\n  * 100;",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Active client count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\n  FROM client_sessions\n  WHERE quit IS NULL;",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Active clients",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT zone_id AS \"Zone ID\",\n  session_id AS \"Session ID\",\n  remote_address AS \"Remote address\",\n  actor_ref AS \"Actor ref\",\n  fingerprint AS \"Fingerprint\",\n  joined as \"Joined\"\n  FROM client_sessions\n  WHERE quit IS NULL\n  ORDER BY joined DESC;",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Projection offset",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT offset\n  FROM liquidity_analytics.tag_offsets\n  WHERE tag = \"zone-event\"\n  ORDER BY offset DESC LIMIT 1",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Event count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT ordering\n  FROM liquidity_journal.journal\n  ORDER BY ordering DESC LIMIT 1;",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Active zone count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\n  FROM zones AS zone\n  WHERE zone.zone_id IN (SELECT zone_id FROM client_sessions WHERE quit IS NULL);",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Active zones",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT LEFT(zone_name_change.name, 20) AS \"Name\",\n  zone.metadata->>'$.currency' AS \"Currency\",\n  zone.zone_id AS \"ID\", zone.created AS \"Created\", zone.modified AS \"Modified\"\n  FROM zones AS zone\n  JOIN zone_name_changes AS zone_name_change\n  ON zone_name_change.change_id = (\n    SELECT change_id\n      FROM zone_name_changes\n      WHERE zone_id = zone.zone_id\n      ORDER BY change_id DESC LIMIT 1\n  )\n  WHERE zone.zone_id IN (SELECT zone_id FROM client_sessions WHERE quit IS NULL)\n  ORDER BY modified DESC;",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Devices",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(created, $histogramWidth) AS time,\n  SUM(1) AS value,\n  (SELECT \"Devices\") AS metric\nFROM devices\nWHERE $__timeFilter(created)\nGROUP BY 1\nORDER BY created ASC",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(entity.joined, $histogramWidth) AS time,\n  SUM(1) AS value,\n  (SELECT \"Connections\") AS metric\nFROM client_sessions AS entity\nJOIN zones AS zone\nON zone.zone_id = entity.zone_id\nWHERE $__timeFilter(entity.joined) OR $__timeFilter(entity.quit)\nGROUP BY 1\nORDER BY entity.joined ASC",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Zones",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(created, $histogramWidth) AS time,\n  SUM(1) AS value,\n  (SELECT \"Zones\") AS metric\nFROM zones\nWHERE $__timeFilter(created)\nGROUP BY 1\nORDER BY created ASC",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Members",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(entity.created, $histogramWidth) AS time,\n  SUM(1) AS value,\n  (SELECT \"Members\") AS metric\nFROM members AS entity\nJOIN zones AS zone\nON zone.zone_id = entity.zone_id\nWHERE $__timeFilter(entity.created)\nGROUP BY 1\nORDER BY entity.created ASC",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Accounts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(entity.created, $histogramWidth) AS time,\n  SUM(1) AS value,\n  (SELECT \"Accounts\") AS metric\nFROM accounts AS entity\nJOIN zones AS zone\nON zone.zone_id = entity.zone_id\nWHERE $__timeFilter(entity.created)\nGROUP BY 1\nORDER BY entity.created ASC",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(entity.created, $histogramWidth) AS time,\n  SUM(1) AS value,\n  (SELECT \"Transactions\") AS metric\nFROM transactions AS entity\nJOIN zones AS zone\nON zone.zone_id = entity.zone_id\nWHERE $__timeFilter(entity.created)\nGROUP BY 1\nORDER BY entity.created ASC",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Zones",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT LEFT(zone_name_change.name, 20) AS \"Name\",\n  zone.metadata->>'$.currency' AS \"Currency\",\n  zone.zone_id AS \"ID\", zone.created AS \"Created\", zone.modified AS \"Modified\"\n  FROM zones AS zone\n  JOIN zone_name_changes AS zone_name_change\n  ON zone_name_change.change_id = (\n    SELECT change_id\n      FROM zone_name_changes\n      WHERE zone_id = zone.zone_id\n      ORDER BY change_id DESC LIMIT 1\n  )\n  WHERE (zone.created >= $__timeFrom() OR zone.modified >= $__timeFrom())\n  ORDER BY modified DESC;",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "NLB active flow count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "net/liquidi-NLB-1MRQXWUN1GEJH/dee44bfd9d79224e"
     },
     "metricName": "ActiveFlowCount",
     "namespace": "AWS/NetworkELB",
     "region": "eu-west-1",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "NLB processed bytes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "net/liquidi-NLB-1MRQXWUN1GEJH/dee44bfd9d79224e"
     },
     "metricName": "ProcessedBytes",
     "namespace": "AWS/NetworkELB",
     "region": "eu-west-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "ECS task CPU",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "liquidity-service-prod-green", "ServiceName": "liquidity-service-prod-green" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-1",
     "statistics": [
      "Average",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "ECS task memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "liquidity-service-prod-green", "ServiceName": "liquidity-service-prod-green" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-1",
     "statistics": [
      "Average",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "RDS reads",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "lr1nlqai5bg2ons" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "region": "eu-west-1",
     "statistics": [
      "Average",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "RDS writes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "lr1nlqai5bg2ons" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "region": "eu-west-1",
     "statistics": [
      "Average",
      "Maximum"
     ]
    }
   ]
  }
 ]
}